services:
  openwebui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    user: "10000"
    volumes:
      - ./data:/app/backend/data
    labels:
      lagoon.type: python-persistent
      lagoon.persistent: /app/backend/data
